//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int job_id { get; set; }
        public string title { get; set; }
        public string qualification { get; set; }
        public string salary { get; set; }
        public string experience { get; set; }
        public string last_date_to_apply { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public string vaccencies { get; set; }
    }
}
