//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int jobapp_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string short_list { get; set; }
        public string doc_path { get; set; }
        public string title { get; set; }
    }
}
