//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public int leaveapp_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public string leave_type { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
    }
}
