//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemarksFromCommittie
    {
        public int remarks_id { get; set; }
        public Nullable<int> c_mem_id { get; set; }
        public Nullable<int> remarks { get; set; }
        public Nullable<int> jobapp_id { get; set; }
    }
}
